version: "3.3"

services:

  grafana:
    image: grafana/grafana:latest-ubuntu                    # Modificar de acordo com a versão desejada
    ports:
      - "3000:3000"                                         # Caso necessário alterar as portas
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app,grafana-piechart-panel 
      GF_SECURITY_ADMIN_PASSWORD: Grafana                  # Senha de acesso ao usuário admin do Grafana
      GF_USERS_DEFAULT_THEME: light
      TZ: America/Recife
    volumes:
      - grafana:/var/lib/grafana

volumes:

  grafana: